on: [push]
name: build
jobs:
  iOS:
    name: Run tests on iOS
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@master
      - name: Build
        run: swift build -v
      - name: Run tests
        run: xcrun xcodebuild test -destination "platform=iOS Simulator,OS=14.2,name=iPhone 8" -project "LocalSplitTests.xcodeproj" -scheme "LocalSplitTests-iOS"
      - name: Test Coverage
        run: bash <(curl -s https://codecov.io/bash)

  macOS:
    name: Build for macOS
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@master
      - name: Build
        run: xcrun xcodebuild build -destination "platform=macOS" -project "LocalSplitTests.xcodeproj" -scheme "LocalSplitTests-macOS"

  watchOS:
    name: Build for watchOS
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@master
      - name: Build
        run: xcrun xcodebuild build -destination "platform=watchOS Simulator,OS=7.1,name=Apple Watch Series 4 - 44mm" -project "LocalSplitTests.xcodeproj" -scheme "LocalSplitTests-watchOS"

  tvOS:
    name: Build for tvOS
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@master
      - name: Build
        run: xcrun xcodebuild build -destination "platform=tvOS Simulator,OS=14.2,name=Apple TV 4K" -project "LocalSplitTests.xcodeproj" -scheme "LocalSplitTests-tvOS"

